services:
  node-installer:
    image: node:20.17.0
    volumes:
      - ./:/home/node/project
    environment:
      npm_config_cache: /home/node/cache
    working_dir: /home/node/project
    user: 1000:1000
    command: npm i

  next:
    image: node:20.17.0
    container_name: next
    volumes:
      - ./:/home/node/project
    ports:
      - 3000:3000
    environment:
      npm_config_cache: /home/node/cache
    working_dir: /home/node/project
    user: 1000:1000
    command: npm run dev:next
    depends_on:
      node-installer:
        condition: service_completed_successfully

  mongo-viewer:
    image: mongo-express
    container_name: mongo-viewer
    ports:
      - 8081:8081
    env_file: ./next/.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    env_file: ./next/.env
    ports:
      - 27017:27017
    volumes:  
      - "mongo_data:/data/db"

volumes:
  mongo_data: